export enum GameState {
    MENU = 'MENU',
    PLACEMENT = 'PLACEMENT',
    BATTLE = 'BATTLE',
    GAME_OVER_INTERNAL = 'GAME_OVER_INTERNAL', 
    POST_BATTLE_REWARDS = 'POST_BATTLE_REWARDS',
    LEVEL_LOST = 'LEVEL_LOST'
}
